# Check if controlplane and node01 have any taints on them that will prevent the pods 
# to be scheduled on them. If there are no taints, the pods can be scheduled on either node.
# So run the following command to check the taints on both nodes.
# root@controlplane:~# kubectl describe nodes controlplane | grep -i taints


apiVersion: v1
kind: Pod
metadata:
  name: toleratedpod1
  labels:
    env: test
spec:
  containers:
    - name: toleratedcontainer1
      image: nginx
  # kubectl taint nodes node1 key1=value1:NoSchedule-
  tolerations:
    - key: "key1"
      operator: "Equal"
      value: "value1"
      effect: "NoSchedule"

---
apiVersion: v1
kind: Pod
metadata: 
  name: toleratedpod2
  labels:
    env: test
spec:
  containers:
  - name: toleratedcontainer2
    image: nginx
    # kubectl taint nodes node1 key2=green:NoSchedule-
  tolerations:
  - key: "key2"
    operator: "Equal"
    value: "green"
    effect: "NoSchedule"