apiVersion: v1
kind: Pod
metadata:
  name: toleratedpod1
  labels:
    env: test
spec:
  containers:
    - name: toleratedcontainer1
      image: nginx
  # kubectl taint nodes node1 key1=value1:NoSchedule-
  tolerations:
    - key: "key1"
      operator: "Equal"
      value: "value1"
      effect: "NoSchedule"

---
apiVersion: v1
kind: Pod
metadata: 
  name: toleratedpod2
  labels:
    env: test
spec:
  containers:
  - name: toleratedcontainer2
    image: nginx
    # kubectl taint nodes node1 key2=green:NoSchedule-
  tolerations:
  - key: "key2"
    operator: "Equal"
    value: "green"
    effect: "NoSchedule"