apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: myapp-service-backend
    type: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000