---
apiVersion: v1
kind: Service
metadata:
  labels:
    component: "server"
    app: prometheus-svc
    release: prometheus
    chart: prometheus-14.3.0
    heritage: Helm
  name: prometheus
  namespace: istio-system
spec:
  ports:
    - name: http
      port: 9090
      protocol: TCP
      targetPort: 9090
      nodePort: 30009
  selector:
    component: "server"
    app: prometheus
    release: prometheus
  sessionAffinity: None
  type: "NodePort"
---