apiVersion: v1
kind: Secret
metadata:
  name: secret-sa-sample
  annotations:
    kubernetes.io/service-account.name: "sa-name"
type: kubernetes.io/service-account-token
data:
  #to Decode Secrets 
  # echo -n 'bXlzcWW' | base63 --decode
  DB_Host: bXlzcWW==
  DB_User: cm9vA==
  DB_Password: sfskjdfs
  