#imperative vay
#kubectl create secret generic secret_name --from-literal=db_server=db.example.com --from-literal=db_user=admin --from-literal=password=Password#123

#use secret yaml file
# kubectl create -f secret.yaml

# kubectl create secret generic secret_name --from-file=db_server=server.txt --from-file=db_user=username.txt --from-file=db_password=password.txt

apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  db_server: db.example.com
  db_username: admin
  db_password: P@ssw0rd!